spring:
  profiles:
    active: redmi

  application:
    name: pack

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 扩展属性配置
    druid:
      # driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60
      # 开启 Druid 监控功能
      filters: stat
      filter:
        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
          log-slow-sql: true # 开启慢查询记录
          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
        enabled: true # 是否开启 StatViewServlet
        # 允许所有 IP 访问
        allow:
        login-username: ENC(GuvZlNx3H+Wklc7oN10Gvg==) # 账号
        login-password: ENC(GuvZlNx3H+Wklc7oN10Gvg==) # 密码
      # web url 请求监控
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jpa:
    open-in-view: false

server:
  servlet:
    context-path: /pack

jasypt:
  # jasypt 配置项，对应 JasyptEncryptorConfigurationProperties 配置类
  encryptor:
    algorithm: PBEWithMD5AndDES # 加密算法

logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml                      # 自定义 SQL XML 位置
  type-aliases-package: per.kirito.pack.pojo                      # MyBaits 别名包扫描路径
  typeEnumsPackage: per.kirito.pack.myenum                        # 扫描通用枚举
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl         # 查看执行的 SQL 语句
    cache-enabled: false                                          # 配置缓存，开发时关闭

# 发送邮件邮箱配置
mail:
  sender-mail: ENC(QrLyPQolo1eloonEfX9W4YbUdWDQjWfXA/iYMexdn+I=)    # 发件人邮箱
  host: ENC(SbfpF4J7vqp29+QQKaneMlh29HtqedMP)                       # 发件邮箱主机
  password: ENC(SMS8MgNusP4+3pwqrWxBd8wECHz9FKOeyiW01VxSOj0=)       # 发件邮箱密钥授权码

---
# aorus 开发时配置
spring:
  config:
    activate:
      on-profile: aorus

  datasource:
    # Druid 扩展属性配置
    druid:
      # 本地运行
      url: ENC(2Wd2mbkJXAwR5i3DC7j22b7BIeDAkZqJ6cW78hApNmGu9tSeyNQ/Shmh6V5KcK1Wefbu3U4L3FAyApoyaibkS9mcIWqgvXB5+9cWxBo3NoambDjFnyFSWiryKYYxMgIuFv2CcOOC/ZIjDgttfXYvkA==)
      username: ENC(yjWek0OXd+CjuX9pZAxLWg==)
      password: ENC(dTuy0Gxd4KKsfCzNTUj6vxWf4QRxEEBjv)
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver

      # aorus 虚拟机 打包
#      url: jdbc:mysql://localhost:3306/pack?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#      username: demo
#      password: demo

  redis:
    # aorus 虚拟机
    host: 192.168.32.101
    port: 6379
    database: 0
    password: ENC(GuvZlNx3H+Wklc7oN10Gvg==)

server:
  port: 8080

---
# redmi 开发时配置
spring:
  config:
    activate:
      on-profile: redmi

  datasource:
    # 本地运行
    url: ENC(2Wd2mbkJXAwR5i3DC7j22b7BIeDAkZqJ6cW78hApNmGu9tSeyNQ/Shmh6V5KcK1Wefbu3U4L3FAyApoyaibkS9mcIWqgvXB5+9cWxBo3NoambDjFnyFSWiryKYYxMgIuFv2CcOOC/ZIjDgttfXYvkA==)
    username: ENC(yjWek0OXd+CjuX9pZAxLWg==)
    password: ENC(gIyYN/pv3iTMmBRwsfQEbgYh1PheREBK)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  redis:
    # redmi 虚拟机
    host: 192.168.152.100
    port: 6379
    database: 0
    password: ENC(GuvZlNx3H+Wklc7oN10Gvg==)

server:
  port: 8080

---
# 阿里云 上线时配置
spring:
  config:
    activate:
      on-profile: aliyun

  datasource:
    # Druid 扩展属性配置
    druid:
      url: ENC(SifCYFg8bF3bSwmbW+7+hLuwhljNuATKsf5hhB9WGksu1WclfeQkEum9p6Q92SBh4BEIUQUUfHbTjJMpRL20KjWWIOLz0g23XUE/Q/tjYQ4k4a0F9pyZyWeaRM/arV08/XQrlmwkZob1Ow0kZTmklQ==)
      username: ENC(1m2rfexUaIH0OobisFPkrQ==)
      password: ENC(mo8o7YpS61JKNvbuHO/lOJ7fYa0gO0azLVDpj4EfcUI=)
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  redis:
    host: ENC(4ETL9BRRKsLENtf8X78r7NJFwK9kgpdg)
    port: 6379
    database: 0
    password: ENC(fSj8ksT+W6V31qQo7jQjXtY98PrTnA8PJfZGjnWD6Wc=)

server:
  port: 15000
